### ISSUE TITLE
Option -b creates wrong model file name

### ISSUE THREAD

**Issue by larsbo** [shopwareLabs/sw-cli-tools#108]
I want to create a plugin with both a backend module and a command. If i use
```
sw plugin:create MyPluginName -b -c
```
it asks for a backend main model and creates the plugin boilerplace where the command and model file names are
```
Commands/'plugin:create' MyPluginName -b -c.php
Models/'plugin:create' MyPluginName -b -c.php
```

Using just the `-b` option creates also a wrong model file called
```
Models/'plugin:create' MyPluginName -b.php
```

Testet on MacOs Sierra inside iTerm2 using zsh with latest cli version `1933dbc`

**Comment by mitelg** [comment]
hey @larsbo 
this should be fixed now. If no Model is given, the suggested default model is taken

**Comment by larsbo** [comment]
awesome, @mitelg ! 💙 🎉
