### ISSUE TITLE
API for retrieving update files

### ISSUE THREAD

**Issue by thueske** [shopwareLabs/sw-cli-tools#112]
Hey! ☺️

Are there any plans to provide an api like [http://update-api.shopware.com/v1/releases/install](http://update-api.shopware.com/v1/releases/install) for all update packages?

I think it's not complex at all and would be very nice for automated processes.

Thanks! 🙏🏼

**Comment by SimonBaeumer** [comment]
Hey @thueske,

an API for `sw-cli-tools` updates is not planned at the moment. Further atm we don't have a versioning... But you are right, at least a good versioning must be added to the `sw-cli-tools`.

https://github.com/shopwareLabs/sw-cli-tools/issues/114

**Comment by mitelg** [comment]
as @SimonBaeumer said: duplicated to #91
