### ISSUE TITLE
Global installation

### ISSUE THREAD

**Issue by MyIgel** [shopwareLabs/sw-cli-tools#113]
When the user is not able to write the sw.phar file (because it is located in /usr/local/bin/) it exits with the following error:

>  [Humbug\SelfUpdate\Exception\FilesystemException]                               
>  The current phar file is not writeable and cannot be replaced: /usr/local/bin/sw.phar.

**Comment by SimonBaeumer** [comment]
Hey @MyIgel,

I don't see any problem with it. If you don't have write access you can't write your `sw.phar`. That's okay and an issue which you should fix in your application. 

A solution is to place the `sw.phar` in `/home/{your_name}/bin/sw.phar` ;)
