### ISSUE TITLE
Java and Ant

### ISSUE THREAD

**Issue by DanielRuf** [shopwareLabs/sw-cli-tools#126]
It would be great to have a pure PHP solution running from the phar so I can use it on more systems. Most do not have these 2 requirements.

**Comment by mitelg** [comment]
@teiling88 are you not working on something like that?

**Comment by shyim** [comment]
We have a internal Pull Request where we change the build process to psh :blush:

**Comment by mitelg** [comment]
FYI: PSH -> https://github.com/shopwareLabs/psh

**Comment by teiling88** [comment]
I'm working on it. But it will only work for the latest Shopware Versions.

**Comment by amenk** [comment]
Is this solved? The readme still mentions the Java requirement but I could not find where it is used.

**Comment by shyim** [comment]
newer shopware versions use a Makefile
