### ISSUE TITLE
interactive mode just does the basic steps

### ISSUE THREAD

**Issue by DanielRuf** [shopwareLabs/sw-cli-tools#127]
https://github.com/shopwareLabs/sw-cli-tools/blob/master/src/Extensions/Shopware/Install/Command/ShopwareInstallReleaseCommand.php#L123

So far the interactive `install:release` command skips many things. Is it planned to add them and what are the default values?

**Comment by DanielRuf** [comment]
Bump.

**Comment by DanielRuf** [comment]
@mitelg I expected that it asks for creating the admin user and doing all the setup steps but these are actually just handled by the web based setup after https://github.com/shopwareLabs/sw-cli-tools/blob/master/src/Extensions/Shopware/Install/Command/ShopwareInstallReleaseCommand.php#L148

**Comment by mitelg** [comment]
ah I see. ok, I will try to have a look at this. I don't want to promise anything, because I have only time for that in our hacktime :wink:
