### ISSUE TITLE
Interactive Mode on sw plugin:create

### ISSUE THREAD

**Issue by thomas-gravel** [shopwareLabs/sw-cli-tools#150]
If you call 
sw plugin:create --haveBackend --haveFrontend SwagTest
then the cli wants to have the model name for the Backend -> Model

If you type in the correct name, you want to have. The created file class is:
'plugin:create' --haveBackend --haveFrontend SwagTest.php

And after you finished, the Backend is a blank white page...

I used the release 0.1.0 on a shopware 5.5.4 (Rev 201812030839)

**Comment by mitelg** [comment]
hey @thomas-gravel 
do you have some error message for us? how do the files look like?

**Comment by thomas-gravel** [comment]
bin/sw.phar plugin:create --haveBackend --haveFrontend --haveWidget SwagTest <ENTER>
Please specify the main model for your backend application: SwagTest\Models\Test

after enter SwagTest 
and finishing

you can type 
bin/console 

and you will get the error message:
PHP Parse error:  syntax error, unexpected ''plugin:create'' (T_CONSTANT_ENCAPSED_STRING), expecting identifier (T_STRING) in custom/plugins/SwagTest/SwagTest.php on line 71

in the php file you can read something funny like: $this->container->get('models')->getClassMetadata(\SwagTest\Models\'plugin:create' --haveBackend --haveFrontend --haveWidget SwagTest::class)

**Comment by mitelg** [comment]
sorry, but I cannot reproduce this issue. I tried the suggest default model class name, and also an own model name

**Comment by larsbo** [comment]
@thomas-gravel do you have the latest version of sw-cli-tools?

**Comment by thomas-gravel** [comment]
I downloaded the assests sw.phar
https://github.com/shopwareLabs/sw-cli-tools/releases

I tried it two times and everytime I get the same issue and error Message.

**Comment by mitelg** [comment]
it seems, there is a problem with the creating of the phar file. it is not the latest version unfortunately. 

try to create the following file: `~/.config/sw-cli-tools/config.yaml` with the following content:
```
update:
  pharUrl: https://shopwarelabs.github.io/sw-cli-tools/sw.phar
  vesionUrl: https://shopwarelabs.github.io/sw-cli-tools/sw.phar.version
  verifyPublicKey: false
  checkOnStartup: true
```

if you then start the command again it should auto-update itself

**Comment by mitelg** [comment]
closed due to inactivity
