### ISSUE TITLE
Release install broken

### ISSUE THREAD

**Issue by OliverSkroblin** [shopwareLabs/sw-cli-tools#16]
Hey,

i got the following error message if i use the sw install:release command:

PHP Warning:  file_get_contents(latest/install/assets/sql/sw4_clean.sql): failed to open stream: No such file or directory in /Users/oliverdenter/bin/sw-cli-tools/src/Extensions/Shopware/Install/Services/Database.php on line 86
PHP Stack trace:
PHP   1. {main}() /Users/oliverdenter/bin/sw-cli-tools/bin/sw:0
PHP   2. Symfony\Component\Console\Application->run() /Users/oliverdenter/bin/sw-cli-tools/bin/sw:19
PHP   3. ShopwareCli\Application->doRun() /Users/oliverdenter/bin/sw-cli-tools/vendor/symfony/console/Symfony/Component/Console/Application.php:124
PHP   4. Symfony\Component\Console\Application->doRun() /Users/oliverdenter/bin/sw-cli-tools/src/Application.php:59
PHP   5. Symfony\Component\Console\Application->doRunCommand() /Users/oliverdenter/bin/sw-cli-tools/vendor/symfony/console/Symfony/Component/Console/Application.php:193
PHP   6. Symfony\Component\Console\Command\Command->run() /Users/oliverdenter/bin/sw-cli-tools/vendor/symfony/console/Symfony/Component/Console/Application.php:887
PHP   7. Shopware\Install\Command\ShopwareInstallReleaseCommand->execute() /Users/oliverdenter/bin/sw-cli-tools/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:252
PHP   8. Shopware\Install\Services\Install\Release->installShopware() /Users/oliverdenter/bin/sw-cli-tools/src/Extensions/Shopware/Install/Command/ShopwareInstallReleaseCommand.php:103
PHP   9. Shopware\Install\Services\Install\Release->setupDatabase() /Users/oliverdenter/bin/sw-cli-tools/src/Extensions/Shopware/Install/Services/Install/Release.php:98
PHP  10. Shopware\Install\Services\Database->importReleaseInstallDeltas() /Users/oliverdenter/bin/sw-cli-tools/src/Extensions/Shopware/Install/Services/Install/Release.php:145
PHP  11. file_get_contents() /Users/oliverdenter/bin/sw-cli-tools/src/Extensions/Shopware/Install/Services/Database.php:86

Warning: file_get_contents(latest/install/assets/sql/sw4_clean.sql): failed to open stream: No such file or directory in /Users/oliverdenter/bin/sw-cli-tools/src/Extensions/Shopware/Install/Services/Database.php on line 86

I think the sw4_clean.sql can not be found. ;)

**Comment by settermjd** [comment]
The sw4_clean.sql file's not in the current repository. Has it been removed for some reason?

**Comment by bcremer** [comment]
The `sw4_clean.sql` is build during our deploy process.

It's a merge of https://github.com/shopware/shopware/blob/master/_sql/install/latest.sql and the migrations https://github.com/shopware/shopware/tree/master/_sql/migrations.

If you want to install a dev version of shopware via github you have to follow the [instructions](https://github.com/shopware/shopware#installation-via-git) in the README.md
