### ISSUE TITLE
http request missing x-shopware-signature

### ISSUE THREAD

**Issue by jwaschkau** [shopwareLabs/sw-cli-tools#163]
![grafik](https://user-images.githubusercontent.com/375650/74252575-2b439c00-4cee-11ea-9cb6-79c1563c2b11.png)

http requests are missing the x-shopware-signature header. This leads to an api verification error.

![grafik](https://user-images.githubusercontent.com/375650/74252927-aefd8880-4cee-11ea-96ad-d95900d799fa.png)

**Comment by mitelg** [comment]
Hey @jwaschkau 
thanks for bringing this up.
I fixed some commands today. did you still have the issue after an update? see this commit:
https://github.com/shopwareLabs/sw-cli-tools/commit/239ca772e46aa5831e070a658e6a1982524bc1e0

if this has not fixed your issue, could please tell me which command you execute and which parameters you entered

**Comment by shyim** [comment]
I have the header on both requests.
Maybe you have something in mitm?
