### ISSUE TITLE
Docs: Add requirements to Readme

### ISSUE THREAD

**Issue by kkrieger85** [shopwareLabs/sw-cli-tools#170]
Please add requirements to readme.md

- PHP Version
- compatibility SW5.x/SW6.x

**Comment by mitelg** [comment]
as you can see in the [travis.yml ](https://github.com/shopwareLabs/sw-cli-tools/blob/master/.travis.yml#L11)currently PHP7.2 is minimum version

right now there are no features for Shopware 6
