### ISSUE TITLE
sw.phar from release 0.2.0 not working in Docker on Windows

### ISSUE THREAD

**Issue by jhit** [shopwareLabs/sw-cli-tools#178]
###  What is broken?
Something is broken in the release 0.2.0 sw.phar file.

 I run this in Docker for Windows from a WSL2 shell:
`php sw.phar install:release -r 5.6.10 -i /var/www/html/shopware --unpack-only -vvv`

and get this error:
```
In Struct.php line 40:

  [OutOfRangeException]
  Unknown property $release in Shopware\Install\Struct\InstallationRequest.


Exception trace:
  at phar:///sw.phar/src/Struct.php:40
 ShopwareCli\Struct->__set() at phar:///sw.phar/src/Struct.php:19
 ShopwareCli\Struct->__construct() at phar:///sw.phar/src/Extensions/Shopware/Install/Command/ShopwareInstallReleaseCommand.php:129
 Shopware\Install\Command\ShopwareInstallReleaseCommand->execute() at phar:///sw.phar/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar:///sw.phar/vendor/symfony/console/Application.php:983
 Symfony\Component\Console\Application->doRunCommand() at phar:///sw.phar/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at phar:///sw.phar/src/Application.php:68
 ShopwareCli\Application->doRun() at phar:///sw.phar/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at phar:///sw.phar/bin/sw:18
 require() at /sw.phar:11

install:release [-r|--release RELEASE] [-i|--install-dir INSTALL-DIR] [--unpack-only] [--skip-download] [--db-host DB-HOST] [--db-port DB-PORT] [--db-socket DB-SOCKET] [--db-user DB-USER] [--db-password DB-PASSWORD] [--db-name DB-NAME] [--no-skip-import] [--shop-locale SHOP-LOCALE] [--shop-host SHOP-HOST] [-p|--shop-path SHOP-PATH] [--shop-name SHOP-NAME] [--shop-email SHOP-EMAIL] [--shop-currency SHOP-CURRENCY] [--skip-admin-creation] [--admin-username ADMIN-USERNAME] [--admin-password ADMIN-PASSWORD] [--admin-email ADMIN-EMAIL] [--admin-locale ADMIN-LOCALE] [--admin-name ADMIN-NAME]
```

### How to reproduce?
OS: Windows
Docker Desktop for Windows with WSL2 enabled.
Shell: WSL2->Ubuntu (with PHP and Composer installed)

```shell
cd ~
mkdir shopware5
cd shopware5
curl https://github.com/shopwareLabs/sw-cli-tools/releases/download/0.2.0/sw.phar --output sw.phar -L
docker run --rm -it --name shopware5 \
    --mount type=bind,source="$(pwd)",target=/var/www/html \
    php:7.4 \
    php /var/www/html/sw.phar install:release -r 5.6.10 -i /var/www/html/shopware --unpack-only -vvv

```

### How to fix it?

I did clone the master of sw-cli-tools and did run composer install and built a new sw.phar. That new sw.phar did work properly.
we are still in WSL Ubuntu Shell in our shopware5 dir.
```shell
git clone https://github.com/shopwareLabs/sw-cli-tools.git
cd sw-cli-tools
composer install
./bin/cleanup_vendor.sh
./bin/download_box.sh
php -dphar.readonly=false ./box.phar build -vv
cd ..
docker run --rm -it --name shopware5 \
    --mount type=bind,source="$(pwd)",target=/var/www/html \
    php:7.4 \
    php /var/www/html/sw-cli-tools/sw.phar install:release -r 5.6.10 -i /var/www/html/shopware --unpack-only -vvv
```

Not sure what the issue with the official sw.phar is, but it would be great if you can re-upload a fixed version.

**Comment by mitelg** [comment]
hey @jhit 

which version do you use exactly? `sw.phar -V`
Did you tried the latest release downloaded from here? http://shopwarelabs.github.io/sw-cli-tools/

**Comment by jhit** [comment]
Hi @mitelg 
The version linked here in Github release page under https://github.com/shopwareLabs/sw-cli-tools/releases/download/0.2.0/sw.phar
reports its version as `sw-cli-tools 0.1.0-18-gb147486`

While the version from http://shopwarelabs.github.io/sw-cli-tools/ reports as 
`sw-cli-tools 0.2.0-17-gecbade0`

I did not realize that the link in the readme links to a different release than the release page here. That is kind of misleading.

The Version `sw-cli-tools 0.1.0-18-gb147486` works without issue.

**Comment by mitelg** [comment]
yeah, we need to fix our deployment I guess :see_no_evil: or tag another release :grimacing: 

FYI: this is not a tool actively by us supported, so fixes will take a bit longer. most of the time, we only fix things, which are erroneous for our own workflows :wink: 
but I will have look, if the workload lets me :smile:

**Comment by jhit** [comment]
I'm fine with the provided phar from your external server. I only use the tool as a automated downloader for my docker setup. Any working version will do :-)
