### ISSUE TITLE
Incompatibile declaration after change in the composer reqs

### ISSUE THREAD

**Issue by xrogers** [shopwareLabs/sw-cli-tools#179]
`PHP Fatal error:  Declaration of Symfony\\Component\\DependencyInjection\\ServiceLocator::get($id) must be compatible with Psr\\Container\\ContainerInterface::get(string $id) in /home/vagrant/sw-cli/vendor/symfony/dependency-injection/ServiceLocator.php on line 27\nPHP Stack trace:\nPHP   1. {main}() /home/vagrant/sw-cli/bin/sw:0\nPHP   2. ShopwareCli\\Application->__construct() /home/vagrant/sw-cli/bin/sw:18\nPHP   3. ShopwareCli\\Application\\DependencyInjection::createContainer() /home/vagrant/sw-cli/src/Application.php:47\nPHP   4. spl_autoload_call() /home/vagrant/sw-cli/src/Application/DependencyInjection.php:42\nPHP   5. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/src/Application/DependencyInjection.php:42\nPHP   6. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322\nPHP   7. include() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444\nPHP   8. spl_autoload_call() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/ContainerBuilder.php:52\nPHP   9. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/ContainerBuilder.php:52\nPHP  10. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322\nPHP  11. include() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444\nPHP  12. class_exists() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php:29\nPHP  13. spl_autoload_call() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php:29\nPHP  14. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php:29\nPHP  15. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322\nPHP  16. include() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444\nPHP  17. spl_autoload_call() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:21\nPHP  18. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:21\nPHP  19. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322\nPHP  20. include() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444”, “stderr_lines”: [“PHP Fatal error:  Declaration of Symfony\\Component\\DependencyInjection\\ServiceLocator::get($id) must be compatible with Psr\\Container\\ContainerInterface::get(string $id) in /home/vagrant/sw-cli/vendor/symfony/dependency-injection/ServiceLocator.php on line 27”, “PHP Stack trace:“, “PHP   1. {main}() /home/vagrant/sw-cli/bin/sw:0”, “PHP   2. ShopwareCli\\Application->__construct() /home/vagrant/sw-cli/bin/sw:18", “PHP   3. ShopwareCli\\Application\\DependencyInjection::createContainer() /home/vagrant/sw-cli/src/Application.php:47”, “PHP   4. spl_autoload_call() /home/vagrant/sw-cli/src/Application/DependencyInjection.php:42", “PHP   5. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/src/Application/DependencyInjection.php:42”, “PHP   6. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322", “PHP   7. include() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444”, “PHP   8. spl_autoload_call() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/ContainerBuilder.php:52", “PHP   9. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/ContainerBuilder.php:52”, “PHP  10. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322", “PHP  11. include() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444”, “PHP  12. class_exists() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php:29", “PHP  13. spl_autoload_call() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php:29”, “PHP  14. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php:29", “PHP  15. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322”, “PHP  16. include() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444", “PHP  17. spl_autoload_call() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:21”, “PHP  18. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:21", “PHP  19. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322”, “PHP  20. include() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444"], “stdout”: “\nFatal error: Declaration of Symfony\\Component\\DependencyInjection\\ServiceLocator::get($id) must be compatible with Psr\\Container\\ContainerInterface::get(string $id) in /home/vagrant/sw-cli/vendor/symfony/dependency-injection/ServiceLocator.php on line 27\n\nCall Stack:\n    0.0003     348168   1. {main}() /home/vagrant/sw-cli/bin/sw:0\n    0.0121     708312   2. ShopwareCli\\Application->__construct() /home/vagrant/sw-cli/bin/sw:18\n    0.0128     775784   3. ShopwareCli\\Application\\DependencyInjection::createContainer() /home/vagrant/sw-cli/src/Application.php:47\n    0.0128     775784   4. spl_autoload_call() /home/vagrant/sw-cli/src/Application/DependencyInjection.php:42\n    0.0128     775864   5. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/src/Application/DependencyInjection.php:42\n    0.0128     775992   6. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322\n    0.0161     786456   7. include(‘/home/vagrant/sw-cli/vendor/symfony/dependency-injection/ContainerBuilder.php’) /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444\n    0.0162     786456   8. spl_autoload_call() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/ContainerBuilder.php:52\n    0.0162     786536   9. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/ContainerBuilder.php:52\n    0.0162     786648  10. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322\n    0.0171     791688  11. include(‘/home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php’) /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444\n    0.0172     792512  12. class_exists() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php:29\n    0.0172     792608  13. spl_autoload_call() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php:29\n    0.0172     792704  14. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php:29\n    0.0173     792832  15. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322\n    0.0175     793864  16. include(‘/home/vagrant/sw-cli/vendor/symfony/dependency-injection/Argument/ServiceLocator.php’) /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444\n    0.0175     793864  17. spl_autoload_call() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:21\n    0.0175     793944  18. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:21\n    0.0175     794056  19. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322\n    0.0179     795144  20. include(‘/home/vagrant/sw-cli/vendor/symfony/dependency-injection/ServiceLocator.php’) /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444", “stdout_lines”: [“”, “Fatal error: Declaration of Symfony\\Component\\DependencyInjection\\ServiceLocator::get($id) must be compatible with Psr\\Container\\ContainerInterface::get(string $id) in /home/vagrant/sw-cli/vendor/symfony/dependency-injection/ServiceLocator.php on line 27”, “”, “Call Stack:“, ”    0.0003     348168   1. {main}() /home/vagrant/sw-cli/bin/sw:0", ”    0.0121     708312   2. ShopwareCli\\Application->__construct() /home/vagrant/sw-cli/bin/sw:18", ”    0.0128     775784   3. ShopwareCli\\Application\\DependencyInjection::createContainer() /home/vagrant/sw-cli/src/Application.php:47", ”    0.0128     775784   4. spl_autoload_call() /home/vagrant/sw-cli/src/Application/DependencyInjection.php:42", ”    0.0128     775864   5. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/src/Application/DependencyInjection.php:42", ”    0.0128     775992   6. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322", ”    0.0161     786456   7. include(‘/home/vagrant/sw-cli/vendor/symfony/dependency-injection/ContainerBuilder.php’) /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444", ”    0.0162     786456   8. spl_autoload_call() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/ContainerBuilder.php:52", ”    0.0162     786536   9. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/ContainerBuilder.php:52", ”    0.0162     786648  10. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322", ”    0.0171     791688  11. include(‘/home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php’) /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444", ”    0.0172     792512  12. class_exists() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php:29", ”    0.0172     792608  13. spl_autoload_call() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php:29", ”    0.0172     792704  14. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Container.php:29", ”    0.0173     792832  15. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322", ”    0.0175     793864  16. include(‘/home/vagrant/sw-cli/vendor/symfony/dependency-injection/Argument/ServiceLocator.php’) /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444", ”    0.0175     793864  17. spl_autoload_call() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:21", ”    0.0175     793944  18. Composer\\Autoload\\ClassLoader->loadClass() /home/vagrant/sw-cli/vendor/symfony/dependency-injection/Argument/ServiceLocator.php:21", ”    0.0175     794056  19. Composer\\Autoload\\includeFile() /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:322", ”    0.0179     795144  20. include(‘/home/vagrant/sw-cli/vendor/symfony/dependency-injection/ServiceLocator.php’) /home/vagrant/sw-cli/vendor/composer/ClassLoader.php:444"`

**Comment by mitelg** [comment]
which command did you execute?

**Comment by xrogers** [comment]
Just `php bin/sw`
I think I know what could be an issue - on this instance we have php7.1.
It would be nice to have tagged (working) version on older php.

**Comment by mitelg** [comment]
you could try using "0.1.0"

beside that you should avoid using unsupported PHP versions :wink:
