### ISSUE TITLE
ExtJs CRUD generator

### ISSUE THREAD

**Issue by Haehnchen** [shopwareLabs/sw-cli-tools#21]
`creating boilerplate code for new plugins`: would be nice if this supports generating extjs crud backend views from a given doctrine entity. similar like the Symfony2 SensioGeneratorBundle.

http://symfony.com/doc/current/bundles/SensioGeneratorBundle/commands/generate_doctrine_crud.html

**Comment by dnoegel** [comment]
See this pull request (WIP) https://github.com/shopwareLabs/sw-cli-tools/pull/27

**Comment by Haehnchen** [comment]
did a quick review. looks fine. thx for publish. pls merge .)
