### ISSUE TITLE
SwagLicense not found

### ISSUE THREAD

**Issue by Rokko11** [shopwareLabs/sw-cli-tools#23]
Hi!
The "install:release"-command fails when Shopware tries to import the Licences:
```
Running license import 
  [RuntimeException]                                                  
  An exception occurred: Plugin by name "SwagLicense" was not found.  
```               

                                                  
In s_core_plugins a plugin called "License" is listed:
```
 {
      "id":"18",
      "namespace":"Core",
      "name":"License",
      "label":"License",
      "source":"Default",
      "description":"",
      "description_long":"",
      "active":"1",
      "added":"2012-08-28 00:00:00",
      "installation_date":"2010-10-18 00:00:00",
      "update_date":"2010-10-18 00:00:00",
      "refresh_date":null,
      "author":"shopware AG",
      "copyright":"Copyright \u00a9 2010, shopware AG",
      "license":"",
      "version":"1",
      "support":"http:\/\/www.shopware.de\/wiki\/",
      "changes":"",
      "link":"http:\/\/www.shopware.de\/",
      "store_version":null,
      "store_date":null,
      "capability_update":"0",
      "capability_install":"0",
      "capability_enable":"0",
      "capability_dummy":"0",
      "update_source":null,
      "update_version":null
   },
```

In the select-statement of sw:plugin:list there is a filter by capability_enable = 1, so the License-Plugin is not listed and so it is not installable.

**Comment by dnoegel** [comment]
Hi,

thanks for mentioning this, it will only work if you have the license manager checked out before, which will automatically happen in our internal setup. For external users this might not be possible yet, so for the time being it will not throw an exception any more but just print the message to STDOUT.
