### ISSUE TITLE
Log path not found when installing latest shopware

### ISSUE THREAD

**Issue by micru** [shopwareLabs/sw-cli-tools#31]
When installing the latests Shopware Version using this cli tools, i`m getting a *Log path not found* Exception. 
Seems as the tools are looking for a wrong log path.

I guess the lookup path in this line https://github.com/shopwareLabs/sw-cli-tools/blob/af5d2ef8a2c85d5c3feffd143e6bc11523a11c76/src/Services/ShopwareInfo.php#L34 should be '**logs**/.htaccess' instead of 'log/.htaccess' and then it should also return **'logs'** instead of 'log'.

**Comment by bcremer** [comment]
Good catch, thank you @micru.

Fixed with https://github.com/shopwareLabs/sw-cli-tools/commit/24ec2a13a0d7bb1b5a9bb6751b0749b4f28a830b.
