### ISSUE TITLE
Release download not working

### ISSUE THREAD

**Issue by jhit** [shopwareLabs/sw-cli-tools#36]
Seems Shopware changed the location of the release packages. install:release is now broken. 
```
[RuntimeException]
Could not open URL 'http://releases.s3.shopware.com/install_5.0.4.zip'.
```

**Comment by bcremer** [comment]
Thanks for Reporting. I am able to reproduce this issue.

In the meanwhile you can use the `latest` keyword to download and install Shopware `5.0.4`.

**Comment by tiagojsag** [comment]
https://github.com/shopwareLabs/sw-cli-tools/pull/45 should cover this
