### ISSUE TITLE
install:release not working

### ISSUE THREAD

**Issue by ssachtleben** [shopwareLabs/sw-cli-tools#53]
Hey,

it seems install:release is not working anymore since http://update-api.shopware.com/v1/releases/install is not reachable.

  [RuntimeException]
  Could not get releases list package

**Comment by bcremer** [comment]
@ssachtleben update-api.shopware.com is currently undergoing maintenance and should be back soon.

**Comment by ssachtleben** [comment]
Ah ok thanks, bad timing :)

**Comment by bcremer** [comment]
It's up again.

**Comment by marcobamert** [comment]
It seems that the release is gone again:
http://releases.s3.shopware.com.s3-eu-west-1.amazonaws.com/install_5.1.3.zip

returns:

```
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>295AD686D548941A</RequestId>
    <HostId>
        tUKRhTIOhmJZbFRFvKPVmXf0Man9ORZTqC4XwoL4es1QvsBBSHvUH56uPWz22UHvh48a1dS/Hxs=
    </HostId>
</Error>
```

**Comment by bcremer** [comment]
@marcobamert http://releases.s3.shopware.com.s3-eu-west-1.amazonaws.com/install_5.1.3.zip is not a valid download URL.

The correct URL is: http://releases.s3.shopware.com.s3.amazonaws.com/install_5.1.3_f089bf38b9a0041b80b24c56a03954dccea5e117.zip
