### ISSUE TITLE
Install for usage system-wide

### ISSUE THREAD

**Issue by PieterScheffers** [shopwareLabs/sw-cli-tools#58]
I wanted to install the sw-cli tool in the /usr/local/bin directory, which is in the path variable, so it makes the command available system wide for all users. This is also the place I have the composer command and some other commands installed.

I have installed the tool with root in /usr/local/bin and then gave it 755 access rights with chmod.
I can now use the tool with the root user.

If I login with a different user, it keeps giving me an exception that /usr/local/bin/sw is not writable.

```
[Humbug\SelfUpdate\Exception\FilesystemException]
The current phar file is not writeable and cannot be replaced: /usr/local/bin/sw.
```

I guess the sw-cli tool is doing a self-update on startup, but with a non-root user it shouldn't.

OS: Ubuntu 14.04

**Comment by bcremer** [comment]
There is a configuration options that prevents the automatic update check, see: https://github.com/shopwareLabs/sw-cli-tools/blob/7065cce31d0fba7c456d167eb54ad7eb5ad7c22c/config.yaml.dist#L89

You should be able to override this section with a custom configuration file in `~/.config/sw-cli-tools/config.yml`.

**Comment by PieterScheffers** [comment]
I tried the following:
~/.config/sw-cli-tools/config.yml and  ~/.config/sw-cli-tools/config.yaml

with contents:
```
update:
  checkOnStartup: false
```

and with all the content from the file you provided.

Both don't work.

**Comment by bcremer** [comment]
As I am on vacation right now maybe @dnoegel can help out.

**Comment by PieterScheffers** [comment]
No problem, it doesn't have priority for me at the moment. Thanks for helping anyway!

**Comment by mitelg** [comment]
hey @PieterScheffers 
is there still a problem?

**Comment by PieterScheffers** [comment]
I haven't tried it anymore, it didn't work for me.

**Comment by mitelg** [comment]
hi @PieterScheffers 
so I will close this issue for now. if you will have this or another issue in the future, don't hesitate opening one again :wink:

**Comment by rodehoed** [comment]
Hi,

This bug is still there. The checkOnStartup on false is completely ignored.
