### ISSUE TITLE
Error generating category demo data

### ISSUE THREAD

**Issue by PieterScheffers** [shopwareLabs/sw-cli-tools#66]
I want to generate some demo data with 'sw generate'.
When generating categories I get the following error:

Using Shopware 5.2.3 with PHP7. (https://github.com/PieterScheffers/Shopware-Docker-Plugin-Development)

>   [Exception]
>   Failed to execute INSERT INTO `s_categories` (`id`, `parent`, `path`, `description`, `position`, `active`) VALUES (1, NULL, '', 'Root', 1, 1),
>                (3, 1, '', 'Deutsch', 3, 1),
>                (4, 3, '|3|', 'quidem', 4, 1),
>                (1000001, 4, '|4|3|', 'omnis', 1000001, 1),
>                (1000002, 4, '|4|3|', 'tempora', 1000002, 1),
>                (1000003, 4, '|4|3|', 'sed', 1000003, 1),
>                (1000004, 4, '|4|3|', 'sequi', 1000004, 1),
>                (5, 4, '|4|3|', 'assumenda', 5, 1),
>                (1000005, 5, '|5|4|3|', 'quas', 1000005, 1),
>                (1000006, 5, '|5|4|3|', 'a', 1000006, 1),
>                (1000007, 4, '|4|3|', 'voluptates', 1000007, 1),
>                (6, 3, '|3|', 'fugiat', 6, 1),
>                (1000008, 6, '|6|3|', 'quia', 1000008, 1),
>                (1000009, 6, '|6|3|', 'reiciendis', 1000009, 1),
>                (1000010, 6, '|6|3|', 'corrupti', 1000010, 1),
>                (1000011, 6, '|6|3|', 'doloribus', 1000011, 1),
>                (1000012, 6, '|6|3|', 'perferendis', 1000012, 1),
>                (1000013, 6, '|6|3|', 'dolores', 1000013, 1),
>                (7, 3, '|3|', 'sunt', 7, 1),
>                (1000014, 7, '|7|3|', 'corporis', 1000014, 1),
>                (1000015, 7, '|7|3|', 'nemo', 1000015, 1),
>                (1000016, 7, '|7|3|', 'sint', 1000016, 1),
>                (1000017, 7, '|7|3|', 'rerum', 1000017, 1),
>                (8, 7, '|7|3|', 'fugiat', 8, 1),
>                (1000018, 8, '|8|7|3|', 'dicta', 1000018, 1),
>                (1000019, 8, '|8|7|3|', 'impedit', 1000019, 1),
>                (1000020, 7, '|7|3|', 'ut', 1000020, 1),
>                (1000021, 3, '|3|', 'aliquid', 1000021, 1) ;
>   Code: HY000,1364,Field 'left' doesn't have a default value

**Comment by mitelg** [comment]
Hi @PieterScheffers do you still got this error with the newest version?

**Comment by PieterScheffers** [comment]
I will test this again, haven't tried it anymore.

**Comment by mitelg** [comment]
I will close this for now. if the problem still exists feel free to open an issue again
