### ISSUE TITLE
Plugin-generator for new plugin-system

### ISSUE THREAD

**Issue by mohrekopp** [shopwareLabs/sw-cli-tools#69]
I want to modify the plugin-creator for generating plugins for the new plugin-system introduced in SW 5.2. 
https://github.com/mohrekopp/sw-cli-tools/tree/new-plugin-creater

Any thoughts?

**Comment by bcremer** [comment]
Looks good. Please go ahead and open a pull request so we can review the code.

**Comment by mitelg** [comment]
hey @mohrekopp 
we already implemented a generation for the new plugin system: 47739e2b7c6b9cd5f938b06a9d2a6908816a0d84
