### ISSUE TITLE
Invalid VCS root mapping in PhpStorm

### ISSUE THREAD

**Issue by mitelg** [shopwareLabs/sw-cli-tools#88]
if you install a plugin via the command `sw plugin:install` and the plugin is build after the new plugin system you will get an error in PhpStorm regarding an invalid VCS root mapping.

> The directory /.../engine/Shopware/Plugins/Local/Frontend/SwagTest is registered as a Git root, but no Git repositories were found there.

**Comment by bcremer** [comment]
Should be fixed here: https://github.com/shopwareLabs/sw-cli-tools/blob/master/src/Extensions/Shopware/Plugin/Services/Install.php#L90

**Comment by mitelg** [comment]
fixed with 7a113be66722bf88406a97ff98c637d15d380997
