### ISSUE TITLE
Official release planned?

### ISSUE THREAD

**Issue by mikewink** [shopwareLabs/sw-cli-tools#91]
Coming from other .php and .js projects where cli is king, I wanted to ask if there are any plans for a final 1.0.0 release of the sw-cli-tools? And if there is, are there any release stoping bugs that need to be fixed before?

I would also like to know if it's okay for you guys if I'd create a [Homebrew](http://brew.sh/) formula once the cli is released. That would make installing the cli even simpler on macOS (Linux).

**Comment by DanielRuf** [comment]
This would be great. I'm still waiting for a stable composer release.

**Comment by mitelg** [comment]
hey @mikewink @DanielRuf 
sorry for the late response :see_no_evil: 
we just made a release for [version 0.1.0](https://github.com/shopwareLabs/sw-cli-tools/releases/tag/0.1.0). We now want to try, to do tags in the future on semver base. We would appreciate a homebrew formula :+1: 

sorry again :v:
