### ISSUE TITLE
Backend does not work after creating plugin with --haveBackend

### ISSUE THREAD

**Issue by mikewink** [shopwareLabs/sw-cli-tools#92]
I created a basic plugin using the CLI and everything went well. The working plugin was created and I could install it into my Shopware 5.2.10 system. But when I wanted to open the backend, I received a 503 error window. 

There is a forum entry that shows the error message in full length.

Link: https://forum.shopware.com/discussion/37227/problem-mit-cli-generiertem-plugin

After digging into the source code of the _Shopware_Controllers_Backend_Application_ class I found the reason for the problem. The _$model_ property of the backend controller needs the full path to the model not just the model name. 
At the moment the property only holds the model name itself. So I guess that's an issue of the CLI that needs to add the full path of the model during plugin creation too.

**Comment by mitelg** [comment]
Hi @mikewink I answered in the forum thread. Of course it could be cool, if you only have to state the model name, but that's not how the command works currently. If you want to change this behavior, feel free to open a PR :blush: :+1:
